import { useGame } from '../game/store';
import { GameIcon } from './GameIcon';

export default function HelpModal() {
  const reset = useGame((s) => s.reset);
  return (
    <div className="text-[13px] leading-relaxed space-y-2">
      <Help><b>Di chuyển:</b> WASD / mũi tên / click vào bản đồ / joystick (mobile). Bấm <b>E</b> để tương tác. Phím <b>+ / −</b> (hoặc nút 🔍 trên thanh HUD) để phóng to / thu nhỏ khung nhìn.</Help>
      <Help><span className="inline-flex items-center gap-1 align-middle"><GameIcon name="sprout" size={17} /> <b>Trồng cây:</b></span> Ra ruộng → <b>E: Cuốc đất</b> → <b>E: Gieo hạt</b> → <b>E: Tưới nước</b> (khô sau 45s) → thu hoạch → bán ở shop. Cây đang lớn có thể <b>bị sâu</b> (ngừng lớn, thanh đỏ) — mua <span className="inline-flex items-center gap-0.5 align-middle"><GameIcon name="pesticide" size={15} /> <b>thuốc trừ sâu</b></span> ở shop rồi bấm <b>E</b> để phun. Khởi đầu 6 ô, mở tối đa <b>45 ô</b> bằng xu + cấp (bấm E vào ô <GameIcon name="lock" size={13} />).</Help>
      <Help><span className="inline-flex items-center gap-1 align-middle"><GameIcon name="pond" size={17} /> <b>Nuôi cá:</b></span> Mua <i>cá con</i> ở shop → ra ao <b>thả</b> (cá tự bơi, khởi đầu nuôi 3 con, tối đa 15) → <b>cho ăn</b> → thu hoạch. <b>Không câu ở ao nuôi!</b> Bấm E vào <b>hòm thư</b> trước ao để xem đàn cá + mở thêm chỗ.</Help>
      <Help><span className="inline-flex items-center gap-1 align-middle"><GameIcon name="rod" size={17} /> <b>Câu sông:</b></span> Shop đã dời ra bãi đất gần bờ sông. Ra 3 bến ở sông cuối map → bấm E → chọn mồi → nhân vật <b>ngồi câu thật</b>. Thấy <GameIcon name="star" size={13} /> báo cắn thì bấm E giật ngay, chậm là cá chạy! Mồi ngon dễ dính cá hiếm.</Help>
      <Help><span className="inline-flex items-center gap-0.5 align-middle"><GameIcon name="chicken" size={17} /><GameIcon name="duck" size={17} /><GameIcon name="cow" size={17} /><GameIcon name="pig" size={17} /><GameIcon name="sheep" size={17} /><GameIcon name="goat" size={17} /><GameIcon name="rabbit" size={17} /> <b>Chăn nuôi:</b></span> 12 loài (gà, vịt, cút, bồ câu, thỏ, ngỗng, ong ở chuồng gà–vịt; bò, heo, cừu, dê, trâu ở trại). Mỗi loài khởi đầu 3 chỗ, nới chuồng tốn nhiều xu. Thú đi lang thang random. Bấm E vào <b>hòm thư</b> trước chuồng để xem + cho ăn + mở thêm chỗ. Cám cao cấp giúp ra sản phẩm nhanh hơn.</Help>
      <Help><b>Thú cưng:</b> đứng gần chó (<b>Vàng</b>, <b>Mực</b>) hoặc mèo (<b>Mimi</b>, <b>Tom</b>, <b>Mun</b>) rồi bấm <b>E</b> để <b>xoa đầu / vuốt ve</b> — pet nhảy cẫng sung sướng!</Help>
      <Help><b>⚡ Làm hàng loạt:</b> bấm nút <b>⚡ Hàng loạt</b> ở thanh farm để <b>cuốc / gieo / tưới / phun / thu</b> cả ruộng và <b>cho ăn / thu sản phẩm</b> cả đàn gia súc + cá chỉ với 1 chạm (tự báo hết hạt/thức ăn/thuốc)!</Help>
      <Help><b>🚗 Xe cộ:</b> ghé <b>Gara Anh Tý</b> ở Khu mua sắm (từ thị trấn đi cổng đông-bắc) — <b>bấm E vào trong nhà</b> xem 3 bục trưng bày, <b>lái thử ngay trong gara</b>! 15 loại xe 3 dòng: <b>🚲 xe đạp từ 10.000 xu</b> → 🛵 xe máy → 🚗 ô tô, càng xịn càng nhanh (siêu xe nhanh hơn gấp đôi đi bộ, có xe gem)! Cầu nâng <b>rửa + bảo dưỡng xe</b>, bảng đồ nghề thử tay nghề có thưởng. Mua xong bấm <b>Lái</b>, chạy khắp farm + thị trấn + khu mua sắm (lái thẳng vào gara được). Bấm <b>X</b> để xuống xe (đang lái thì không làm ruộng được).</Help>
      <Help><b>Thị trấn:</b> đứng gần bạn + cùng bấm 1 hành động (👋 chào, 🤝 bắt tay, 🤗 ôm, 💋 hun, 🥊 đánh yêu) → 2 nhân vật <b>thực sự lao vào nhau</b> diễn hoạt ảnh!</Help>
      <Help><b>🏠 Nhà trong thị trấn:</b> đi tới cửa + bấm <b>E</b> để vào trong đi lại thật! Mỗi nhà có việc riêng: quán mèo (món hôm nay x2 XP, hũ tip, cây mèo, vuốt đủ 3 mèo lĩnh 50 xu), hội quán (chuông họp làng, bàn chè hóng chuyện, lộc làng), shop (đố vui, thùng sale, thuê đồ diễn, stylist chấm điểm), sân khấu (trống hội, disco, diễn đúng đèn yêu cầu + ENCORE x1.5 tip), nhà cô Ba (đơn đặt hàng, hái rau, ảnh gia đình, bé Út), nhà chú Tám (đạp xe ve chai, dò radio, đố mẹo, giám định), <b>casino</b> (chơi nhanh với máy, slot giờ vàng x2, vòng quay, bar), <b>gara Anh Tý</b> (bục lái thử xe, cầu nâng rửa + bảo dưỡng, thử tay nghề)! Ghé đủ <b>11 nhà/ngày</b> (thị trấn 5 + khu mua sắm 6) ra bảng hội quán <b>đóng dấu nhận 150 xu + 1 gem</b>!</Help>
      <Help><b>🎡 Khu Mua sắm & Giải trí:</b> từ thị trấn đi <b>cổng đông-bắc</b>! Có <b>gara, casino, shop lưu niệm, nhà vé số</b> (vé 50 xu + <b>vé cào 20 xu</b> trúng liền), <b>sông câu cá</b> 3 bến, <b>trường đua xe tối đa 5 người — lái xe thật 5 vòng quanh track, thấy xe nhau chạy</b> (vô địch +300 xu +1 gem) và <b>hang ma sói</b>!</Help>
      <Help><b>🏆 Giải câu cá:</b> bảng nổi góc phải (farm/thị trấn/khu mua sắm) → <b>mở giải 3 phút</b>, ra bến sông (sông mới ở khu mua sắm!) giật cá tính tổng giá trị, BXH live, top 3 tự nhận thưởng (🥇600xu+3gem)!</Help>
      <Help><b>🐺 Ma sói (5–12 người):</b> vào <b>Hang Ma Sói</b> ở khu mua sắm (hoặc bấm nút 🐺 menu Chơi) → mở/tham gia bàn, chia vai bí mật (sói/tiên tri/bảo vệ/dân), đêm hành động lén — ngày bàn luận + bỏ phiếu treo. Phe thắng +300 xu +1 gem!</Help>
      <Help><b>Lệnh ẩn trong chat thị trấn:</b> gõ <code>pupu</code> → <b>ném trứng thối</b> vào đứa đứng gần nhất (trúng đầu dính bết + choáng!), <code>kiki</code> → <b>chó khổng lồ</b> chạy tới vòng quanh bạn 2 vòng rồi chạy đi, <code>mimi</code> → <b>đàn mèo</b> từ mọi phía chạy tới vây quanh bạn, <code>kemkem</code> → triệu hồi <b>mèo cam Kem</b> đi theo bạn mãi mãi ở cả farm + thị trấn (đúng 1 con, gõ lại cũng không thêm)!</Help>
      <Help><span className="inline-flex items-center gap-1 align-middle"><GameIcon name="calendar" size={17} /> <b>Ngày/đêm</b></span> tự chạy ~4 phút/ngày. Cây lớn theo thời gian thực, nhớ tưới đều!</Help>
      <Help><b>Multiplayer kiểu Avatar (phím V):</b> thấy bạn bè đi lại cùng map, chat có bóng thoại. Mỗi người có <b>mã farm 6 ký tự</b> — chia sẻ link <code>?visit=MÃ</code> để bạn qua <b>thăm farm</b> (chỉ xem). Chưa cấu hình Supabase thì mở 2 tab cùng trình duyệt là chơi chung được (làng local).</Help>
      <Help><span className="inline-flex items-center gap-1 align-middle"><GameIcon name="gift" size={17} /> <b>Giftcode (phím G):</b></span> bấm biểu tượng <b>quà</b> trên thanh HUD rồi <b>tự nhập code</b> để nhận quà bí mật (xu, gem, vật phẩm…). Mỗi code nhận 1 lần / farm.</Help>
      <Help><b>Kiến trúc mới:</b> React + Zustand + Canvas engine tách lớp — thêm cây/cá/map mới chỉ cần sửa <code>data.ts</code>/<code>world.ts</code>.</Help>
      <button className="pixel-btn !text-[10px]" onClick={() => { if (confirm('Xóa hết chơi lại?')) reset(); }}>Chơi lại từ đầu</button>
    </div>
  );
}

function Help({ children }: { children: React.ReactNode }) {
  return <div className="bg-white border-2 border-[#2b2117] rounded-lg p-2.5">{children}</div>;
}
